dist: trusty
language: go

go:
  - 1.9

branches:
  only:
  - master

env:
  - FFMPEGBIN="$HOME/ffmpeg_bin" DIST="$HOME/dist"

before_install:
  # Download and extract binaries
  # Windows 64-bit
  - mkdir -p "$FFMPEGBIN/win64" "$FFMPEGBIN/win32" "$FFMPEGBIN/osx"
  - curl -o "$FFMPEGBIN/win64/ffmpeg_win64.zip" 'https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.3.3-win64-static.zip'
  - unzip -jq "$FFMPEGBIN/win64/ffmpeg_win64.zip" '*/bin/ffmpeg.exe' -d "$FFMPEGBIN/win64/" && ls "$FFMPEGBIN/win64/ffmpeg.exe"
  # Windows 32-bit
  - curl -o "$FFMPEGBIN/win32/ffmpeg_win32.zip" 'https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-3.3.3-win32-static.zip'
  - unzip -jq "$FFMPEGBIN/win32/ffmpeg_win32.zip" '*/bin/ffmpeg.exe' -d "$FFMPEGBIN/win32/" && ls "$FFMPEGBIN/win32/ffmpeg.exe"
  # MacOS
  - curl -o "$FFMPEGBIN/osx/ffmpeg_osx.zip" 'http://www.ffmpegmac.net/resources/Lion_Mountain_Lion_Mavericks_Yosemite_El-Captain_15.05.2017.zip'
  - unzip "$FFMPEGBIN/osx/ffmpeg_osx.zip" 'ffmpeg' -d "$FFMPEGBIN/osx/" && ls "$FFMPEGBIN/osx/ffmpeg"
  - go get github.com/golang/lint && go install github.com/golang/lint/golint

script:
  - golint kdramadl.go
  - go tool vet kdramadl.go
  - mkdir -p "$DIST"
  - GOOS=linux GOARCH=386 go build -o "$DIST/kdramadl_linux_386" 'kdramadl.go'
  - GOOS=linux GOARCH=amd64 go build -o "$DIST/kdramadl_linux_amd64" 'kdramadl.go'
  - GOOS=darwin GOARCH=amd64 go build -o "$DIST/kdramadl_osx_amd64" 'kdramadl.go'
  - GOOS=windows GOARCH=386 go build -o "$DIST/kdramadl_386.exe" 'kdramadl.go'
  - GOOS=windows GOARCH=amd64 go build -o "$DIST/kdramadl_amd64.exe" 'kdramadl.go'
  - cd "$DIST"
  - ls -ltr
  # Check binary
  - ./kdramadl_linux_amd64 -h
  # Package Linux versions
  - mv 'kdramadl_linux_386' 'kdramadl' && tar -zcf 'kdramadl_linux_386.tar.gz' 'kdramadl' && rm 'kdramadl'
  - mv 'kdramadl_linux_amd64' 'kdramadl' && tar -zcf 'kdramadl_linux_amd64.tar.gz' 'kdramadl' && rm 'kdramadl'
  # Package MacOS versions
  - mv 'kdramadl_osx_amd64' 'kdramadl' && cp -p "$FFMPEGBIN/osx/ffmpeg" .
    && zip -jq 'kdramadl_macos_amd64.zip' 'kdramadl'
    && zip -jq 'kdramadl_macos_amd64_ffmpeg.zip' 'kdramadl' 'ffmpeg'
    && rm 'kdramadl' 'ffmpeg'
  # Package Window 32-bit versions
  - mv 'kdramadl_386.exe' 'kdramadl.exe' && cp -p "$FFMPEGBIN/win32/ffmpeg.exe" .
    && zip -jq 'kkdramadl_windows_32bit.zip' 'kdramadl.exe'
    && zip -jq 'kkdramadl_windows_32bit_ffmpeg.zip' 'kdramadl.exe' 'ffmpeg.exe'
    && rm 'kdramadl.exe' 'ffmpeg.exe'
  # Package Window 64-bit versions
  - mv 'kdramadl_amd64.exe' 'kdramadl.exe' && cp -p "$FFMPEGBIN/win64/ffmpeg.exe" .
    && zip -jq 'kkdramadl_windows_64bit.zip' 'kdramadl.exe'
    && zip -jq 'kkdramadl_windows_64but_ffmpeg.zip' 'kdramadl.exe' 'ffmpeg.exe'
    && rm 'kdramadl.exe' 'ffmpeg.exe'
  - ls -ltr "$DIST/kdramadl_*.*"
